### ISSUE TITLE
Don't use strings to represent state

### ISSUE THREAD

**Issue by eoriont** [C0BBL3/space-empires#10]
In your `combat_engine.py` file, I noticed you use strings for `player.status`. It would be better if you make it either an integer or a boolean, like `player.status = 0` or `player.is_dead = True`. This way, you don't have to worry about capitalization or misspelling the state.

**Comment by C0BBL3** [comment]
I can fix the ships' status but no the player, because there are 3 status' that is, has, Playing, Not Playing, and Deceased. (also for log testing reasons but this is not as important)
