### ISSUE TITLE
Write real tests!

### ISSUE THREAD

**Issue by eoriont** [C0BBL3/space-empires#11]
Obviously, your tests pass right now. It would be better, however, if you actually stepped through the game using functions to check the equality of specific variables. This makes it much easier to add stuff to your test, and makes stuff much easier to debug. If Justin ever doesn't give us a test log, or changes up the style of it slightly, you will have to rewrite a bunch of code or test against your own output, which is like testing if True is True.

**Comment by C0BBL3** [comment]
fixed
