### ISSUE TITLE
Change ship_class into actual class type

### ISSUE THREAD

**Issue by eoriont** [C0BBL3/space-empires#15]
In your `player.py` class, I noticed you have this massive function for selecting a certain class of ship based on an ID you made. ID's are very helpful in that they can help identify which type the ship is, but what comes with it is an un-intuitive style of coding, where instead of saying something like `if type(ship) == Scout:` you end up saying `if ship_id == 1:` which isn't welcoming for people who want to understand your code or trying to review it. There is an easy fix, however. You can set a variable to an actual class type. Take this for example:
```
class Scout(Unit):
    pass

ship = Scout(<blah blah>)

ship_type = type(ship)

new_scout = ship_type(<blah blah>)
```
Using this style makes your code more readable and comprehensible, and it is also shorter which I know you love.

**Comment by C0BBL3** [comment]
I'll probably do something similar but with isinstance instead, also I understand it better and for the untrained eye.

**Comment by C0BBL3** [comment]
redundant but fixed anyway
