### ISSUE TITLE
Should pass ships involved in combat, not board, into CombatEngine

### ISSUE THREAD

**Issue by jpskycak** [C0BBL3/space-empires#2]
src/combat-engine.py -- __init__.py

You should only be passing a certain set of ships into CombatEngine not the whole board.

from Riley

**Comment by C0BBL3** [comment]
I use the board to get the dictionary of ships on the board so I don't need to pass 3 different ships I can just do self.board...

**Comment by C0BBL3** [comment]
obsolete now cause game_dict
