### ISSUE TITLE
Name your functions better in basic_strategy

### ISSUE THREAD

**Issue by eoriont** [C0BBL3/space-empires#27]
You have a couple functions, like `simple_sort`, `max_value`, and `ship_1_fires_first` which I can't figure out what they do by name, unless I actually dive into the dumpster fire below.  (KIDDING)

Rename them to more self-explanatory things, like `sort_ships_by_x` or `determine_first_ship` or `determine_strongest_ship`. Also, remember since this is a helper class, it makes more sense to call it `determine_x` instead of just `x`.

**Comment by C0BBL3** [comment]
fixed
