### ISSUE TITLE
Beautify engine files

### ISSUE THREAD

**Issue by eoriont** [C0BBL3/space-empires#32]
In each of the `movement_engine.py`, `combat_engine.py`, and `economic_engine.py`, you have these massive blocks of code that contain all the main functionality. 

For you, it's probably easy to read. However, for us reviewers, it isn't. You should make it a habit to add in a comment every couple lines. For example, at the beginning of the function `complete_all_taxes` in `EconomicEngine`, you have a couple lines that compute the maintenance and income for each player. You should put a comment above them that explains that that's what you're doing.

Comments, are nice, but sometimes they aren't enough. Usually, for each comment-code block, you want to separate it from other "blocks" with blank newlines, to really show the reader that you are working on a new thing now. It's almost like paragraphs in an essay, where the essay is your function, and the paragraphs are the little blocks.

Last but definitely not least, make sure to use your space with statements. I see you call many `if` statements on just 1 line, which first of all, goes against PEP8, and second, bloats the line. For example, you should change this:
```py
if self.asc_or_dsc != 'random': self.current_roll = self.rolls[self.dice_roll_index]
else: self.current_roll = math.floor(10*random.random()) + 1
```
into this:
```py
# Set current dice roll
if self.asc_or_dsc != 'random': 
    self.current_roll = self.rolls[self.dice_roll_index]
else: 
    self.current_roll = math.floor(10*random.random()) + 1
```
(Notice the comment as well!) (Taken from `CombatEngine`)

That being said, if you have a list comprehension, or a "black box" function, it's completely fine to keep that on one line, as they are pretty idiomatic, despite the length.

**Comment by C0BBL3** [comment]
fixed
